---
- hosts: naming
  strategy: free
  serial: 4
  vars_files:
    - vars/references.yml
  roles:
    - naming
- hosts: java
  strategy: free
  serial: 2
  vars_files:
    - vars/references.yml
  roles:
    - java
- hosts: python
  strategy: free
  serial: 2
  vars_files:
    - vars/references.yml
  roles:
    - python
- hosts: webapp
  strategy: free
  vars_files:
    - vars/webapp.yml
    - vars/references.yml
  roles:
    - webapp
- hosts: kafka
  strategy: free
  vars:
    - java_version: 11
  vars_files:
    - vars/kafka.yml
    - vars/references.yml
  roles:
    - kafka
- hosts: druid
  vars:
    - java_version: 1.8.0
  vars_files:
    - vars/druid.yml
    - vars/references.yml
  roles:
    - druid
- hosts: superset
  strategy: free
  vars_files:
    - vars/superset.yml
    - vars/references.yml
  roles:
    - superset
