---
- hosts: all
  become: yes
  vars_files:
    - vars/references.yml
  roles:
    - naming
- hosts: webapp
  become: yes
  vars_files:
    - vars/webapp.yml
    - vars/references.yml
  roles:
    - python
    - webapp
- hosts: kafka
  become: yes
  vars:
    - java_version: 11
  vars_files:
    - vars/kafka.yml
    - vars/references.yml
  roles:
    - java
    - kafka
- hosts: druid
  become: yes
  vars:
    - java_version: 1.8.0
  vars_files:
    - vars/druid.yml
    - vars/references.yml
  roles:
    - java
    - druid
- hosts: superset
  become: yes
  vars_files:
    - vars/superset.yml
    - vars/references.yml
  roles:
    - python
    - superset
