---
- name: debug
  debug:
    var: references
- name: Naming | Install package avahi
  yum:
    name: "{{ packages }}"
    state: latest
  become: true
  vars:
    packages:
    - avahi
- name: Naming | Ensure correct hostname advertisement
  lineinfile:
    path: /etc/avahi/avahi-daemon.conf
    regexp: "^.*host-name=.*"
    line: "host-name={{ references[inventory_hostname].hostname }}"
    owner: root
    group: root
    mode: '0644'
- name: Naming | Ensure correct host advertisement
  lineinfile:
    path: /etc/avahi/avahi-daemon.conf
    regexp: "^.*domain-name=.*"
    line: "domain-name={{references[inventory_hostname].domainname }}"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Naming
- name: Naming | Flush handlers
  meta: flush_handlers
- name: Naming | Set hostname
  hostname:
    name: "{{ references[inventory_hostname].fqdn }}"
- name: Naming | Add myself to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_facts['default_ipv4']['address'] }}.*"
    line: "{{ ansible_facts['default_ipv4']['address'] }} {{ references[inventory_hostname].hostname }} {{ references[inventory_hostname].fqdn }}"
    state: present
- name: Naming | Set hostname as facts for further reuse
  set_fact:
    fqdn: "{{ references[inventory_hostname].fqdn }}"
    hostname: "{{ references[inventory_hostname].hostname }}"
    domain: "{{ references[inventory_hostname].domainname }}"
    nodename: "{{ references[inventory_hostname].fqdn }}"
    cacheable: yes
