---
- name: Restart Zookeeper
  service: name=kafka-zookeeper.service state=restarted enabled=yes
  become: yes
- name: Restart Kafka
  service: name=kafka.service state=restarted enabled=yes
  become: yes