---
- name: Kafka | Check if archive exists
  stat:
    path: "{{ home }}/{{ archive_filename }}"
  register: kafka_archive_exists
- name: Kafka | Download binary distribution
  get_url:
    url: "https://downloads.apache.org/kafka/{{ kafka_version }}/{{ archive_filename }}"
    dest: "{{ home }}"
  when: kafka_archive_exists.stat.exists == false
- name: Kafka | Check if dir exists
  stat:
    path: "{{ kafka_dir }}"
  register: kafka_dir_exists
- name: Kafka | Extract archive
  unarchive:
    src: "{{ home }}/{{ archive_filename }}"
    dest: "{{ home }}"
    remote_src: yes
  when: kafka_dir_exists.stat.exists == false
- name: Kafka | Create Zookeeper unit file
  template: src=kafka-zookeeper.service.j2 dest=/lib/systemd/system/kafka-zookeeper.service mode=644
  become: yes
  notify:
    - Restart Zookeeper
- name: Kafka | Create Kafka unit file
  template: src=kafka.service.j2 dest=/lib/systemd/system/kafka.service mode=644
  become: yes
- name: Kafka | Create Kafka config file
  template:
    src: kafka-server.properties.j2
    dest: "{{ kafka_dir }}/config/kafka-server.properties"
    mode: 0644
  notify:
    - Restart Kafka
- name: Kafka | Flush handlers
  meta: flush_handlers
- name: Kafka | Create Kafka topic
  ansible.builtin.shell: "{{ kafka_dir }}/bin/kafka-topics.sh --create --topic {{ references[inventory_hostname].topic }} --bootstrap-server {{ references[inventory_hostname].fqdn }}:9092"
  register: create_topic_out
  failed_when:
    - create_topic_out.rc != 0
    - "'already exists' not in create_topic_out.stdout"