---
- name: Kafka | Download binary distribution
  get_url:
    url: "https://downloads.apache.org/kafka/{{ kafka_version }}/{{ archive_filename }}"
    dest: "{{ home }}"
- name: Kafka | Extract archive
  unarchive:
    src: "{{ home }}/{{ archive_filename }}"
    dest: "{{ home }}"
    remote_src: yes
    owner: "{{ user }}"
    group: "{{ group }}"
- name: Kafka | Create Zookeeper unit file
  template: src=kafka-zookeeper.service.j2 dest=/lib/systemd/system/kafka-zookeeper.service mode=644
  notify:
    - Restart Zookeeper
- name: Kafka | Create Kafka unit file
  template: src=kafka.service.j2 dest=/lib/systemd/system/kafka.service mode=644
- name: Kafka | Create Kafka config file
  template:
    src: kafka-server.properties.j2
    dest: "{{ kafka_dir }}/config/kafka-server.properties"
    mode: 0644
    owner: "{{ user }}"
    group: "{{ group }}"
  notify:
    - Restart Kafka
- name: Kafka | Flush handlers
  meta: flush_handlers
- name: Kafka | Create Kafka topic
  shell:
    cmd: "{{ kafka_dir }}/bin/kafka-topics.sh --create --topic {{ kafka_topic }} --bootstrap-server {{ nodename }}:9092"