---
- name: setup required packages
  yum:
    name: "{{ packages }}"
    state: latest
  become: true
  vars:
    packages:
    - python38-psycopg2
    - python38-pip
    - python3-virtualenv
    - python38-devel
    - gcc
    - gcc-c++
