---
- name: Avahi | Install package avahi
  yum:
    name: "{{ packages }}"
    state: latest
  become: true
  vars:
    packages:
    - avahi
- name: Avahi | Ensure correct hostname advertisement
  lineinfile:
    path: /etc/avahi/avahi-daemon.conf
    regexp: "^.*host-name=.*"
    line: "host-name={{ hostname }}"
    owner: root
    group: root
    mode: '0644'
- name: Avahi | Ensure correct host advertisement
  lineinfile:
    path: /etc/avahi/avahi-daemon.conf
    regexp: "^.*domain-name=.*"
    line: "domain-name={{ domainname }}"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart Avahi
- name: Avahi | Flush handlers
  meta: flush_handlers
- name: Avahi | Set hostname
  hostname:
    name: "{{ hostname }}.{{ domainname }}"
- name: Avahi | Add myself to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_facts['default_ipv4']['address'] }}.*"
    line: "{{ ansible_facts['default_ipv4']['address'] }} {{ hostname }} {{ hostname }}.{{ domainname }}"
    state: present
- name: Avahi | Set hostname as facts for further reuse
  set_fact:
    fqdn: "{{ hostname }}.{{ domainname }}"
    hostname: "{{ hostname }}"
    domain: "{{ domainname }}"
    nodename: "{{ hostname }}.{{ domainname }}"
    cacheable: yes
