---
- name: Restart Superset
  service: name=superset.service state=restarted enabled=yes
  become: yes
  become_user: root
- name: Restart Nginx
  service: name=nginx.service state=restarted enabled=yes
  become: yes
  become_user: root