---
- name: Java | setup required packages
  yum:
    name: "{{ packages }}"
    state: latest
  become: true
  vars:
    packages:
    - java-11-openjdk-headless.x86_64
- name: Java | Get JAVA_HOME dir
  shell: dirname $(dirname $(readlink $(readlink /usr/bin/java)))
  register: java_home
- name: Java | Edit system-level bashrc to put JAVA_HOME env var
  lineinfile:
    path: /etc/profile.d/sh.local
    line: "export JAVA_HOME={{ java_home.stdout }}"
