---
- name: Druid | Check if archive exists
  stat:
    path: "{{ home }}/{{ archive_filename }}"
  register: druid_archive_exists
- name: Druid | Download binary distribution
  get_url:
    url: "https://downloads.apache.org/druid/{{ druid_version }}/{{ archive_filename }}"
    dest: "{{ home }}"
  when: druid_archive_exists.stat.exists == false
- name: Druid | Check if dir exists
  stat:
    path: "{{ druid_dir }}"
  register: druid_dir_exists
- name: Druid | Extract archive
  unarchive:
    src: "{{ home }}/{{ archive_filename }}"
    dest: "{{ home }}"
    remote_src: yes
  when: druid_dir_exists.stat.exists == false
- name: Druid | Create Druid unit file
  template: src=druid.service.j2 dest=/lib/systemd/system/druid.service mode=644
  become: yes
  notify:
    - Restart Druid
- name: Druid | Flush handlers
  meta: flush_handlers
- name: Druid | Copy ingestion spec
  template: src=supervisor-spec.json.j2 dest="{{ home }}/supervisor-spec.json" mode=644
- name: Druid | Pause for 20 seconds before submitting injection spec
  pause:
    seconds: 20
- name: Druid | Post ingestion spec
  uri:
    url: "http://{{ references['druid_vm'].fqdn }}:8081/druid/indexer/v1/supervisor"
    method: POST
    src: "{{ home }}/supervisor-spec.json"
    status_code: 200
    body_format: json
    remote_src: yes
